### ISSUE TITLE
Cannot configure presets

### ISSUE THREAD

**Issue by slesinger** [JurajNyiri/HomeAssistant-Atrea#12]
Hello,

I want to select only certain presets but it is not possible to save it du to following error:

```
User input malformed: value must be one of [] for dictionary value @ data['presets']
```

### How to reproduce:
1. Add Atrea integration
2. Go to Settings -> Integrations -> select box Atrea.
3. Click ```[Configure]``` button
4. All presents are selected by default. Select any combination of presets
5. Click ```[Submit]``` button

### Device info
```
EC ECV380
by ATREA s.r.o.
Firmware: 2.3.19
Hardware: 35B183824
```

Component version: 6.1.0
HA version: Home Assistant 2022.7.6

In spite many presets are available, only those actually supported by the unit are offered in climate widget drop-down. -> low priority issue for me.

Thank you
Honza

**Comment by JurajNyiri** [comment]
I am not able to replicate this, when I click save it saves. Could you please post more details?

**Comment by slesinger** [comment]
There is no log output in home-assistant.log upon saving the configuration dialog. There http error 400 visible in the browser.

**Request in curl format**
```
curl 'http://ha.doma:8123/api/config/config_entries/options/flow/0249149cd3c25673e809268e45a7d226' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9,cs;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Cookie: PHPSESSID=8m12hoe05h23d3m0kd6g4rl1uf' \
  -H 'Origin: http://ha.doma:8123' \
  -H 'Referer: http://ha.doma:8123/config/integrations' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.167 Safari/537.36' \
  -H 'authorization: Bearer eyJ0eXAvv4' \
  --data-raw '{"password":"pass","name":"Atrea","fan_modes":"12,20,30,40,50,60,70,80,90,100","presets":null,"Off":true,"Automatic":true,"Ventilation":true,"Circulation and Ventilation":true,"Circulation":true,"Night precooling":true,"Disbalance":true,"Overpressure":true,"Periodic ventilation":true,"Startup":true,"Rundown":true,"Defrosting":true,"External":true,"HP defrosting":true,"IN1":true,"IN2":true,"D1":true,"D2":true,"D3":true,"D4":true}' \
  --compressed \
  --insecure
```

**Raw response**
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Content-Length: 95
Content-Encoding: deflate
Date: Fri, 29 Jul 2022 19:00:43 GMT
Server: Python/3.10 aiohttp/3.8.1

{"message":"User input malformed: value must be one of [] for dictionary value @ data['presets']"}
```

I have also tried from various browsers on Linux desktop and Chrome on Android.
Thank you

**Comment by JurajNyiri** [comment]
Hey, this should now be fixed in [6.1.2](https://github.com/JurajNyiri/HomeAssistant-Atrea/releases/tag/6.1.2)!

Please let me know if it works for you now!

**Comment by miakcz** [comment]
Hi, seems I have the same problem. I can configure fan modes, but I can't change the preset modes. Any idea what could be wrong?

Great integration by the way, thank you!

**Comment by JurajNyiri** [comment]
@miakcz Hi, please open new issue and provide more information.
