### ISSUE TITLE
Atrea DUPLEX 360 Pro-V.aM.CF

### ISSUE THREAD

**Issue by dinojascur** [JurajNyiri/HomeAssistant-Atrea#16]
Hi, just bought Atrea unit Atrea DUPLEX 360 Pro-V.aM.CF, fw. aMCE-v.2.0.3 and not able to connect to HA.

**Comment by dinojascur** [comment]
any plans for support it ? 

it says "IP address is not a supported Atrea unit"

**Comment by JurajNyiri** [comment]
Hi, It's not possible for me to find out what is wrong without owning the unit or having access to it. Try posting more information, how does the UI look like, screenshots etc.

**Comment by dinojascur** [comment]
Hi Juraj, see the screenshots of gui. Let me know in case you need anything else.

![image](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/67243036/716fe9ff-049b-492f-8772-72269648c2ad)
![image](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/67243036/9ce66486-c7a8-4d7d-b3ca-d357c682f0f7)
![image](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/67243036/14df33d8-565b-45f5-b4e7-179a2ce54b7e)

**Comment by JurajNyiri** [comment]
That system is not compatible unfortunately.
