### ISSUE TITLE
Can't change Presets

### ISSUE THREAD

**Issue by miakcz** [JurajNyiri/HomeAssistant-Atrea#20]
**How to reproduce**
In _Integration entries_ click on _configure_. If I change fan modes and click on Submit, it works. But if I change for example D1 preset (have it selected) it doesn't appear in frontend and also I can't set it using Developer tools service call climate.set_preset_mode. It gives me: 
_Preset mode D1 is not valid. Valid preset modes are: Off, Automatic, Ventilation, Night precooling._

**Home assistant**

Core
2024.1.3
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

**Atrea unit**
ECV380 RD5

**Integration**
2.3.25

**Comment by JurajNyiri** [comment]
Please provide screenshots of what you see in web interface

**Comment by miakcz** [comment]
![atrea-preset-setting](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/38094863/066cd783-209c-496b-a1ee-3c1f7f8740d3)
![atrea-thermostat](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/38094863/4a3970ec-1e70-4307-b946-31239b4032dd)
![atrea-unit](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/38094863/5e3f6485-370c-4def-b659-b8f1353b7eeb)

**Comment by JurajNyiri** [comment]
Screenshots form the web interface of atrea where you change the modes.

**Comment by miakcz** [comment]
OK, I get it now. Sorry, my bad. I thought that I can force the D1 preset but it is limited to the preset done in Atrea. So that means I can't set the D1...D4 settings, am I right?
 
![atrea-setting](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/38094863/1fc0105f-a467-47e7-944b-b112f134fadb)

**Comment by JurajNyiri** [comment]
That is not currently supported. I am not sure what the d settings are and what is their purpose?

**Comment by miakcz** [comment]
D1, D2, D3 and D4 are external inputs - youconnect them to push buttons (physical). For example toilet - it overrides for preset time current mode to let's say Ventilation, fan speed 80% for 300 seconds.
![atrea-inputs](https://github.com/JurajNyiri/HomeAssistant-Atrea/assets/38094863/9543341b-268a-4aff-a945-908f233975f7)

**Comment by JurajNyiri** [comment]
These can be replaced by automations in Home Assistant which are better in every way. I would recommend to use those instead.

**Comment by miakcz** [comment]
Ok, thank you
